spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: MAXSCORP
    password: MAXSCORP
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: AuthHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate          # Liquibase owns the schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        default_batch_fetch_size: 20

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  scheduling:
    enabled: true

jwt:
  secret: ${JWT_SECRET:KrgKgIge3IBLqxZhs47sZyivqYZz5t6UjXf0/D1ezeQ=}
  access-token:
    expiry: ${JWT_ACCESS_TOKEN_EXPIRY:900000}
  refresh-token:
    expiry: ${JWT_REFRESH_TOKEN_EXPIRY:604800000}
